In [11]:
# importing important libraries

import cv2
import numpy as np
import matplotlib.pyplot as plt

In [12]:
# defining a kernel using numpy

first_kernel = np.array([
    [1,1,1],
    [1,1,1],
    [1,1,1]
])

print(first_kernel)
print(first_kernel[0][0]) 


[[1 1 1]
 [1 1 1]
 [1 1 1]]
1


In [18]:
# making a convolution operation by hand
# to make it simple just make one for 3x3 * 3x3
kernel1 = np.array([
    [0,-1,0],
    [-1,5,-1],
    [0,-1,0]
])

image1= np.array([
    [2,2,2],
    [2,3,2],
    [2,2,2]
])

image2= np.array([
    [2,2,2],
    [2,1,2],
    [2,2,2]
])

def convolute(image,kernel):
    output=0
    for i in range(3):
        for j in range(3):
            output+=(image[i][j])*(kernel[i][j])
    print(output)

convolute(image1,kernel1)

7


In [29]:
# trying convoluting on a local image

my_image=cv2.imread(r"lotus.jpeg")
kernel = np.ones((5,5), np.float32) / 25

filtered = cv2.filter2D(
    my_image, # our image matrix
    -1, 
    kernel
)
# print(kernel)
cv2.imshow("Our First Convolution",filtered)
cv2.waitKey(5000)
cv2.destroyAllWindows()

In [ ]:
# mean blur
# compare different kernel sizes

In [38]:
# gaussian blur
gaussian = cv2.GaussianBlur(
    my_image,
    (5,5),
    0
)
cv2.imshow("Gaussian ",gaussian)
cv2.waitKey(5000)
cv2.destroyAllWindows()

In [36]:
# sharpen edges

sharpen_kernel = np.array([
    [0,-1,0],
    [-1,5,-1],
    [0,-1,0]
])
sharpen = cv2.filter2D(
    my_image,
    -1,
    sharpen_kernel
)
cv2.imshow("Sharp edges ",sharpen)
cv2.waitKey(5000)
cv2.destroyAllWindows()

In [35]:
edge_kernel = np.array([
    [-1,-1,-1],
    [-1,8,-1],
    [-1,-1,-1]
])

edge = cv2.filter2D(
    sharpen, # our image matrix
    -1, 
    edge_kernel
)
cv2.imshow("Edge Detection ",edge)
cv2.waitKey(5000)
cv2.destroyAllWindows()

In [40]:
kernel = np.ones((3,3), np.float32) / 9
sample=my_image
for i in range(10):
    sample= cv2.filter2D(sample,-1,kernel)
cv2.imshow("10 times Mean",sample)
cv2.imshow("Gaussian ",gaussian)
cv2.waitKey(5000)
cv2.destroyAllWindows()